/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M1
 * Generated at: 2016-03-23 03:15:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.io.InputStreamReader;
import java.io.FileInputStream;
import java.awt.Desktop;
import java.util.List;
import java.util.ArrayList;
import java.util.Scanner;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.Writer;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.util.*;
import java.text.*;
import com.hitachigst.prb.te.teweb.*;
import com.hitachigst.prb.itd.itdtools.util.*;
import com.hitachigst.prb.te.testtimetool.*;

public final class testcode_005ftesttrialtracker_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


  String subjectshow="";  String ownershow=""; String emailshow="";  String productshow =""; 
  String showtrialid="";  String showtestcode=""; String showtestid=""; String showpfcode=""; 
  String showhddnum=""; String showprocess=""; String showstdate=""; String showendate=""; 
  String  showinorex="";int count=0;int val = 0; int j=0;String line;String addlist = "";
  String stdate="";String copylist = ""; String copylistfolder = ""; String powerpointfolder="";
  String enddate=""; String allshow=""; String yieldshow=""; String testtimeshows="";
  String chisqaureshow=""; String testcodeAshow=""; String testcodeBshow="";String powerpointlink2="";
  String modeltypeshow=""; String samplingshow=""; String mfgidshows="";String powerpointlink1="";
  String testtimestracks1=""; String copylistfolders = "";


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/PageLayout/footerlayout.jsp", Long.valueOf(1455876871114L));
    _jspx_dependants.put("/PageLayout/testcode_righttoplayout.jsp", Long.valueOf(1458092814077L));
    _jspx_dependants.put("/PageLayout/../testcode_topmenu.jsp", Long.valueOf(1457697117567L));
    _jspx_dependants.put("/PageLayout/testcode_lefttoplayout.jsp", Long.valueOf(1455876871152L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hitachigst.prb.te.teweb");
    _jspx_imports_packages.add("com.hitachigst.prb.te.testtimetool");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.hitachigst.prb.itd.itdtools.util");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.awt.Desktop");
    _jspx_imports_classes.add("java.io.BufferedWriter");
    _jspx_imports_classes.add("java.io.FileWriter");
    _jspx_imports_classes.add("java.io.FileOutputStream");
    _jspx_imports_classes.add("java.util.Scanner");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.io.FileInputStream");
    _jspx_imports_classes.add("java.io.InputStreamReader");
    _jspx_imports_classes.add("java.io.FileNotFoundException");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.io.Writer");
    _jspx_imports_classes.add("java.io.FileReader");
    _jspx_imports_classes.add("java.io.BufferedReader");
    _jspx_imports_classes.add("java.nio.channels.FileChannel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=TIS-620");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 30720, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("   \r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" />\r\n");
      out.write("<meta name=\"author\" content=\"Luka Cvrk (www.solucija.com)\" />\r\n");
      out.write("<meta name=\"description\" content=\"My Site\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"key, words\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
  
String version=""; String webname="";
webname=IniFilesReader.getReturnProperties("Local.Application","Application Name"); 
version=TeWebVersionControl.getVersion();

 String tracker = request.getParameter("hidden_tracker");
 String summary = request.getParameter("hidden_summary");
 String add = request.getParameter("hidden_add");

     if(tracker==null&&summary==null){
    
    tracker = "checked"  ;
    summary  = ""  ;
      
    }
    if(add!=null){
    tracker = "checked"  ;
     summary = ""  ;
    }
   
 



    

      out.write("\r\n");
      out.write("<title>\r\n");
 out.println(webname); 
      out.write("\r\n");
      out.write("</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"DATA-INF/CSS/style.css\" media=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"JSAX-INF/amcharts.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function MM_reloadPage(init) {  //reloads the window if Nav4 resized\r\n");
      out.write("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {\r\n");
      out.write("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}\r\n");
      out.write("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload(); }\r\n");
      out.write("\r\n");
      out.write("MM_reloadPage(true);\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    h1 {text-shadow:0px 0px #000000;}\r\n");
      out.write("    h4{ color: #000; background-color: #444; text-shadow: 0px 0px 0px #000000; }\r\n");
      out.write("    body{ background-color:#fff; font-family:Arial, Verdana; font-size:12px; color:#444444; margin:0; }\r\n");
      out.write("    form{ width: 1000px; padding-left: 150px; }\r\n");
      out.write("    form *{ background: transparent; }\r\n");
      out.write("    label{ display: block; width: 100px; margin: 0 auto; font-weight: bold; color: #666; padding-top: 15px;}\r\n");
      out.write("    input[type=checkbox]{background: none; -webkit-border-radius: 0; -moz-border-radius: 0; border-radius: 0; padding:0;\r\n");
      out.write("          margin: 0; width: 15px; }\r\n");
      out.write("    fieldset{ -webkit-border-radius: 8px; -moz-border-radius: 8px; border-radius: 8px; margin-top: 15px; color: #000; }\r\n");
      out.write("    input[ type=submit]{\r\n");
      out.write("  border:1px solid #616261; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;font-size:12px;font-family:arial, helvetica, sans-serif; padding: 10px 10px 10px 10px; text-decoration:none; display:inline-block;text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: #FFFFFF;\r\n");
      out.write("   background-color: #7d7e7d; background-image: -webkit-gradient(linear, left top, left bottom, from(#7d7e7d), to(#0e0e0e));\r\n");
      out.write("   background-image: -webkit-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("   background-image: -moz-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("   background-image: -o-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("   background-image: linear-gradient(to bottom, #7d7e7d, #0e0e0e);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#7d7e7d, endColorstr=#0e0e0e);\r\n");
      out.write("  }\r\n");
      out.write("  input[type=submit]:hover{\r\n");
      out.write("   border:1px solid #5ca6c4;\r\n");
      out.write("   background-color: #82bbd1; background-image: -webkit-gradient(linear, left top, left bottom, from(#82bbd1), to(#193b61));\r\n");
      out.write("   background-image: -webkit-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: -moz-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: -o-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: linear-gradient(to bottom, #82bbd1, #193b61);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#82bbd1, endColorstr=#193b61);\r\n");
      out.write("  }\r\n");
      out.write("    input[type=button]{\r\n");
      out.write("      border:1px solid #616261; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;font-size:12px;font-family:arial, helvetica, sans-serif; padding: 10px 10px 10px 10px; text-decoration:none; display:inline-block;text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: #FFFFFF;\r\n");
      out.write("       background-color: #7d7e7d; background-image: -webkit-gradient(linear, left top, left bottom, from(#7d7e7d), to(#0e0e0e));\r\n");
      out.write("       background-image: -webkit-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("       background-image: -moz-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("       background-image: -ms-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("       background-image: -o-linear-gradient(top, #7d7e7d, #0e0e0e);\r\n");
      out.write("       background-image: linear-gradient(to bottom, #7d7e7d, #0e0e0e);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#7d7e7d, endColorstr=#0e0e0e);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("  input[type=button]:hover{\r\n");
      out.write("   border:1px solid #5ca6c4;\r\n");
      out.write("   background-color: #82bbd1; background-image: -webkit-gradient(linear, left top, left bottom, from(#82bbd1), to(#193b61));\r\n");
      out.write("   background-image: -webkit-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: -moz-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: -o-linear-gradient(top, #82bbd1, #193b61);\r\n");
      out.write("   background-image: linear-gradient(to bottom, #82bbd1, #193b61);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#82bbd1, endColorstr=#193b61);\r\n");
      out.write("  }\r\n");
      out.write("    .show { display: block;  }\r\n");
      out.write("    .hide { display: none; }\r\n");
      out.write("  \r\n");
      out.write("          .styled-select {\r\n");
      out.write("          width: 500px;\r\n");
      out.write("          height: 34px;\r\n");
      out.write("          overflow: hidden;\r\n");
      out.write("          <!--background: url(DATA-INF/Image/Select.png) no-repeat ;-->\r\n");
      out.write("          border-radius: 10px;\r\n");
      out.write("          }\r\n");
      out.write("          .styled-select select {\r\n");
      out.write("          background: transparent;\r\n");
      out.write("          width: 500px;\r\n");
      out.write("          padding: 5px;\r\n");
      out.write("          border: 1px solid #CCC;\r\n");
      out.write("          font-size: 14px;\r\n");
      out.write("          height: 34px;\r\n");
      out.write("          font-weight: bold;\r\n");
      out.write("          outline:0px;\r\n");
      out.write("          -webkit-appearance: none;\r\n");
      out.write("          border-radius: 10px;\r\n");
      out.write("          }\r\n");
      out.write("          .styled-select option {\r\n");
      out.write("          background: lightgrey;\r\n");
      out.write("          width: 500px;\r\n");
      out.write("          padding: 5px;\r\n");
      out.write("          border: 1px solid #CCC;\r\n");
      out.write("          font-size: 14px;\r\n");
      out.write("          height: 34px;\r\n");
      out.write("          outline:0px;\r\n");
      out.write("          -webkit-appearance: none;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("    .button[disabled], .button[disabled]:hover, .button[disabled]:active{\r\n");
      out.write("    border-color: #eaeaea;\r\n");
      out.write("    background: #fafafa;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("    position: static;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    /* Usually, !important should be avoided but here it's really needed :) */\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    text-shadow: none !important;\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("        function showtrack(){\r\n");
      out.write("  document.getElementById('table2').className='hide';\r\n");
      out.write("  document.getElementById('table1').className='show';\r\n");
      out.write("  document.getElementById('table3').className='hide';\r\n");
      out.write("  document.getElementById('powerpoint').className='hide';\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("        function hidetrack(){\r\n");
      out.write("  document.getElementById('table2').className='show';\r\n");
      out.write("  document.getElementById('table1').className='hide';\r\n");
      out.write("  document.getElementById('table3').className='hide';\r\n");
      out.write("  document.getElementById('powerpoint').className='hide';\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("      function addSubmits(){ var frm = document.form1; frm.action=\"testcode_testtrialtracker.jsp\"; frm.submit();}\r\n");
      out.write("      function addSubmitss(){ var frm = document.form1; frm.action=\"testcode_testtrialtracker.jsp\"; frm.submit();}\r\n");
      out.write("      function change1(){document.getElementById('runscript1').disabled=false;\r\n");
      out.write("       document.getElementById('del1').disabled=false;\r\n");
      out.write("          document.getElementById('edittracker').disabled=false;}\r\n");
      out.write("      function change2(){\r\n");
      out.write("         document.getElementById('runscript2').disabled=false;\r\n");
      out.write("           document.getElementById('del3').disabled=false;\r\n");
      out.write("       document.getElementById('editsummary').disabled=false;\r\n");
      out.write("             document.getElementById('powerpoint').className='show';\r\n");
      out.write("              document.getElementById('table3').className='show';\r\n");
      out.write("        var selectBox = document.getElementById(\"select\");\r\n");
      out.write("        var selectedValue = selectBox.options[selectBox.selectedIndex].value;\r\n");
      out.write("        var res = selectedValue.replace(\".csv\",\".htm\");\r\n");
      out.write("        var directories =\"DATA-INF/Result_htm/\"+res;\r\n");
      out.write("        var z=\"DATA-INF/Result_htm/No_Resultssss.html\"\r\n");
      out.write("        document.getElementById('my_selec').value = document.getElementById('select').value\r\n");
      out.write("        var x= document.getElementById('my_selec').value;\r\n");
      out.write("        var y=document.getElementById('select').value;\r\n");
      out.write("        if(x==y){\r\n");
      out.write("              window.open(directories,'powerpoint');\r\n");
      out.write("           }else{\r\n");
      out.write("            window.open(z,'powerpoint');\r\n");
      out.write("          }\r\n");
      out.write("       \r\n");
      out.write("       }\r\n");
      out.write("      function checkederror(){\r\n");
      out.write("        alert(\"Error!!! Run Unsuccessful\");\r\n");
      out.write("         addSubmits();\r\n");
      out.write("      } \r\n");
      out.write("        function checkederror1(){\r\n");
      out.write("        alert(\"Error!!! Another User  Execute or Summary File\");\r\n");
      out.write("         addSubmits();\r\n");
      out.write("      } \r\n");
      out.write("    function wait(){  \r\n");
      out.write("              var showonload= document.getElementById('showinload');\r\n");
      out.write("              showonload.className = 'show';\r\n");
      out.write("                var save= document.getElementById('save');\r\n");
      out.write("              save.disabled=true;\r\n");
      out.write("                var del1= document.getElementById('del1');\r\n");
      out.write("              del1.disabled=true;\r\n");
      out.write("                var summary= document.getElementById('byEdit');\r\n");
      out.write("              summary.disabled=true;\r\n");
      out.write("        document.getElementById('editsummary').disabled=true;\r\n");
      out.write("                document.getElementById('edittracker').disabled=true;\r\n");
      out.write("            }\r\n");
      out.write("   function wait1(){  \r\n");
      out.write("              var showonload= document.getElementById('showonload');\r\n");
      out.write("                          showonload.className = 'show';\r\n");
      out.write("               var save1= document.getElementById('save1');\r\n");
      out.write("              save1.disabled=true;\r\n");
      out.write("                var del3= document.getElementById('del3');\r\n");
      out.write("              del3.disabled=true;\r\n");
      out.write("                var track= document.getElementById('track');\r\n");
      out.write("              track.disabled=true;\r\n");
      out.write("        document.getElementById('editsummary').disabled=true;\r\n");
      out.write("                document.getElementById('edittracker').disabled=true;\r\n");
      out.write("            }\r\n");
      out.write("       function show3s(){alert(\"Run Successfully\");\r\n");
      out.write("      addSubmits();\r\n");
      out.write("                           }\r\n");
      out.write("      function show4s(){alert(\"Run Successfully\");\r\n");
      out.write("      addSubmitss();\r\n");
      out.write("      \r\n");
      out.write("                           }\r\n");
      out.write("   \r\n");
      out.write("    function changeFunc1() {\r\n");
      out.write("        var selectBox = document.getElementById(\"select\");\r\n");
      out.write("        var selectedValue = selectBox.options[selectBox.selectedIndex].value;\r\n");
      out.write("        var res1 = selectedValue.replace(\".csv\",\".ppt\");\r\n");
      out.write("        var directoriess =\"DATA-INF/Result_htm/\"+res1;\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("        window.open(directoriess,'download2');\r\n");
      out.write("       \r\n");
      out.write("       }\r\n");
      out.write("    function changeFunc2() {\r\n");
      out.write("        var selectBox = document.getElementById(\"select\");\r\n");
      out.write("        var selectedValue = selectBox.options[selectBox.selectedIndex].value;\r\n");
      out.write("        var res2 = selectedValue.replace(\".csv\",\".xls\");\r\n");
      out.write("        var directoriesss =\"DATA-INF/Result_htm/\"+res2;\r\n");
      out.write("        window.open(directoriesss,'download1');\r\n");
      out.write("       }\r\n");
      out.write("       function status1(){\r\n");
      out.write("     \r\n");
      out.write("     document.forms[0].action = 'testcode_testrialtracker_codition.jsp'; return true;\r\n");
      out.write("       }\r\n");
      out.write("        function status2(){\r\n");
      out.write("     document.forms[0].action = 'testcode_testrialtracker_codition.jsp'; return true;\r\n");
      out.write("     \r\n");
      out.write("       }\r\n");
      out.write("          function statusedit1(){\r\n");
      out.write("   \r\n");
      out.write("         document.forms[0].action = 'testcode_testrialtracker_codition.jsp'; return true;\r\n");
      out.write("    \r\n");
      out.write("       }\r\n");
      out.write("        function statusedit2(){\r\n");
      out.write("     document.forms[0].action = 'testcode_testrialtracker_codition.jsp'; return true;\r\n");
      out.write("     \r\n");
      out.write("       }\r\n");
      out.write("       function show2s(){ \r\n");
      out.write("          \r\n");
      out.write("        alert(\" Delete Successfully\"); \r\n");
      out.write("        addSubmits();\r\n");
      out.write("      } \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  >\r\n");
      out.write("\r\n");
      out.write("<!-- ----------------------Te Logo--------------------------- -->\r\n");
      out.write("<div id=\"Layer1\" style=\"position:absolute; left:3px; top:3px; width:84px; height:70px; z-index:1\"><img src=\"DATA-INF/Image/telogo.jpg\" width=\"275\" height=\"100%\" /></div> \r\n");
      out.write("<!-- -------------------------------------------------------- -->\r\n");
      out.write("<!--  <div id=\"Layer2\" style=\"position:absolute; left:460px; top:255px; width:505px; height:46px; z-index:2\"> </div>  -->\r\n");
String menumode="testcode_testtrialtracker.jsp";
      out.write("  \r\n");
      out.write("<!-- ---------------------------------Left Layout -------------- -->\r\n");
      out.write("<div id=\"contentleft\">\r\n");
      out.write("  <div id=\"left\"> \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!-- ============================================Top Layout============================================================================== -->\t\r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write("      <table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"><!-- <img  src=\"DATA-INF/Image/telogo.jpg\" alt=\"Your Logo\" title=\"Your Logo\" /> --></td>\r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t  <td width=\"34%\"></td>\r\n");
      out.write("\t\t</tr>   \t \r\n");
      out.write("     </table>  \r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div id=\"headerL\"></div>  \r\n");
      out.write("   </div> \r\n");
      out.write("\r\n");
      out.write("<!-- ============================================Top Layout============================================================================== -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"right\"> ");
      out.write("\r\n");
      out.write("<!-- ============================================Top Layout============================================================================== -->\t\r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write("      <table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"></td>\t\t  \r\n");
      out.write("\t\t  <td width=\"23%\"><img src=\"DATA-INF/Image/telogoempty.jpg\" alt=\"Your Logo\" title=\"Your Logo\" /></td>\r\n");
      out.write("\t\t  <td width=\"40%\"> <p>Version : ");
out.println(version); 
      out.write(" | <a href=\"#Top\">Logon: ");
out.println(session.getAttribute("s_username").toString().trim());
      out.write("</a><br /></p> </td>\t  \r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"></td>\t\t  \r\n");
      out.write("\t\t  <td width=\"23%\"></td>\r\n");
      out.write("\t\t  <td width=\"40%\"></td>\r\n");
      out.write("\t\t</tr>   \t \r\n");
      out.write("     </table>  \r\n");
      out.write("     <div id=\"header-container\">\t\t  \t\r\n");
      out.write("\t\t  ");
      out.write("     <ul id=\"nav\"> \r\n");
      out.write("\t  ");

	    if (menumode.equals("testcode_home.jsp")){
	  
      out.write("\r\n");
      out.write("\t\t   <li><a href=\"home.jsp\">Home</a><li>      \r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a>\r\n");
      out.write("\t\t   <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>  \r\n");
      out.write("\t\t   \r\n");
      out.write("\t \r\n");
      out.write("\t   ");

	   } else if (menumode.equals("testcode_enterpriserelatedwebsite.jsp")) {
	   
      out.write("\r\n");
      out.write("\t   \t   <li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a>\r\n");
      out.write("\t\t   <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>    \r\n");
      out.write("\t   ");

	    }else if (menumode.equals("testcode_testtimemonitor.jsp")) {
	   
      out.write("\r\n");
      out.write("\t       <li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a> \r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\t\t   \r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>    \r\n");
      out.write("\t\t");

		}else if(menumode.equals("testcode_testtrialtracker.jsp")){
		
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a> \r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\t\t   \r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>\r\n");
      out.write("\t   ");

		}else if(menumode.equals("testcode_testtimeworkweek.jsp")){
		
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a> \r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\t\t   \r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>\r\n");
      out.write("\t\t   ");

		}
	   
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br class=\"clear\" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t  </div>\t \r\n");
      out.write("\t</div>\r\n");
      out.write("\t \r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("<form name=\"form1\" id=\"form1\" method=\"post\" action=\"\" align=\"center\" >\r\n");
      out.write("     <input type=\"hidden\" name=\"hidden_tracker\" />\r\n");
      out.write("      <input type=\"hidden\" name=\"hidden_summary\" />\r\n");
      out.write("      <input type=\"hidden\" name=\"hidden_add\" />\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <h1>&nbsp;</h1>\r\n");
      out.write("\r\n");
      out.write("    <fieldset align=\"center\"  >\r\n");
      out.write("  <legend >\r\n");
      out.write("    <h1>Mode</h1>\r\n");
      out.write("        </legend>\r\n");
      out.write("    <table  border=\"0\" bordercolor=\"#00000\">\r\n");
      out.write("      <tr> \r\n");
      out.write("    <td width=\"200\"></td>\r\n");
      out.write("    <td width=\"29\" height=\"41\"><input type=\"radio\" name=\"reportOption\" id=\"track\" value=\"byAdd\"");
      out.print(tracker);
      out.write(" onclick=\"showtrack();\" /></td>\r\n");
      out.write("    <td width=\"60\"><h4>Tracker</h4></td> \r\n");
      out.write("    <td width=\"20\"><input type=\"radio\" name=\"reportOption\" id=\"byEdit\" value=\"Sum\"  ");
      out.print(summary);
      out.write(" onclick=\"hidetrack();\" /></td>\r\n");
      out.write("          <td width=\"66\"><h4>Summary</h4></td> \r\n");
      out.write("    <td width=\"1000\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    \r\n");
      out.write("    </table>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("\r\n");
      out.write("    <fieldset align=\"center\" id=\"table1\" class=\"show\">\r\n");
      out.write("              \r\n");
      out.write("    <legend >\r\n");
      out.write("      <h1>Tracker</h1>\r\n");
      out.write("        </legend>\r\n");
      out.write("    <table border=\"0\" bordercolor=\"#00000\"   >\r\n");
      out.write("      <tr>\r\n");
      out.write("    <td></td>\r\n");
      out.write("         <td width=\"600\" id=\"texture\" ><h4>Select Tracker CSV File: \r\n");
      out.write("\r\n");
      out.write("    <div class=\"styled-select\"> \r\n");
      out.write("        <select width=\"1000\"  name=\"my_select1\" id=\"select1\" class=\"select\" onchange=\"change1();\" >\r\n");
      out.write("            <option >Please Select Condition</option>\r\n");
      out.write("     <!--------------------------------Event show Condition File-------------------------------------------------------------------->\r\n");
      out.write("   ");


     File appFolder = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\");
                
                         File[] list = appFolder.listFiles();
                         
							 for(int i=0;i<list.length;i++)
							{
								  File file = list[i];   
								   if (file.isFile() && file.getName().endsWith(".csv")) {
			
								  addlist = list[i].getName();
				
								  out.print("<option id=\"\"value=\"" +addlist+ "\">"+addlist+"</option>");
											  }   
								   if(request.getParameter("del1")!=null&&request.getParameter("runscript1")==null&&request.getParameter("runscript2")==null&&request.getParameter("del3")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
								
									   String selection=request.getParameter("my_select1");
									   
									  if(selection.equals(addlist )){
								
										list[i].delete();
												  subjectshow ="";
												  ownershow ="";
												  emailshow="";
												  allshow="";
												  yieldshow="";
												  testtimeshows="";
												  chisqaureshow="";
												  productshow="";
												  modeltypeshow="";
												  showtrialid ="";
												  showtestcode="";
												  testcodeAshow="";
												  testcodeBshow="";
												  showtestid="";
												  showpfcode="";
												  showinorex="";
												  showhddnum="";
												  showprocess="";
												  showstdate="";
												  showendate="";
												  samplingshow="";
												  mfgidshows="";
												  stdate="";
												  enddate="";
										}
									}
							}  

              if(request.getParameter("del1")!=null&&request.getParameter("runscript1")==null&&request.getParameter("runscript2")==null&&
                request.getParameter("del3")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
                                out.println("<script type='text/javascript'>");
                                out.println("show2s();");
                                out.println("</script>"); 
                              }
 //  <!--------------------------------Event Write select All Condition File-------------------------------------------------------------------->
                              try{
                                      
                                String pathoptionss = "C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\OneCondition\\OnlythisCoditiontion.csv";
                                        File optionfiles = new File(pathoptionss);
                                     Writer objWritersss = new BufferedWriter(new FileWriter(optionfiles));
                                       File copyFiless = new File("C:\\Tomcat_9.0\\webapps\\TrialTrackerStatus\\Condition\\OneCondition\\");
                                  File[] copylistfiless = copyFiless.listFiles();
                                          //  for(int f=1;f<copylistfiless.length;f++) {
                                             objWritersss.write("All"+"\n");
                                            
                                        //}
                                        objWritersss.flush();
                                        objWritersss.close();
                                      }catch(IOException  e){  
                                          e.printStackTrace();  
                                       }    
   //  <!--------------------------------Event Check run One File -------------------------------------------------------------------->
                              if(request.getParameter("runscript1")!=null&&request.getParameter("runscript2")==null&&request.getParameter("del1")==null&&request.getParameter("del3")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
                                      subjectshow ="";
                                          ownershow ="";
                                          emailshow="";
                                          allshow="";
                                          yieldshow="";
                                          testtimeshows="";
                                          chisqaureshow="";
                                          productshow="";
                                          modeltypeshow="";
                                          showtrialid ="";
                                          showtestcode="";
                                          testcodeAshow="";
                                          testcodeBshow="";
                                          showtestid="";
                                          showpfcode="";
                                          showinorex="";
                                          showhddnum="";
                                          showprocess="";
                                          showstdate="";
                                          showendate="";
                                          samplingshow="";
                                          mfgidshows="";
                                          stdate="";
                                          enddate="";
                                  
                                          String lines;
                                          String pidInfos ="";
                                          Process k =Runtime.getRuntime().exec(System.getenv("windir") +"\\system32\\"+"tasklist.exe");
                                          BufferedReader inputs =  new BufferedReader(new InputStreamReader(k.getInputStream()));

                                          while ((lines = inputs.readLine()) != null) {
                                           pidInfos+=lines; 
                                          }

                                          inputs.close();

                                          if(pidInfos.contains("MacroTrigger.exe"))
                                          {
                                          
                                          out.println("<script>");
                                           out.println("checkederror1();");
                                          out.println("</script>");
                           
                                
                              }else{
                                try{
                                      String pathoptions = "C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\OneCondition\\OnlythisCoditiontion.csv";
                                      File optionfiles = new File(pathoptions);
                                      Writer objWriterss = new BufferedWriter(new FileWriter(optionfiles));
                                      File copyFiles = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\");
                                      File[] copylistfiles = copyFiles.listFiles();
                                      File deleteFiles = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\OneCondition\\OnlythisCoditiontion.csv");
                                      if(deleteFiles.exists()){
                                    deleteFiles.delete();
                                     }
                                            for(int f=0;f<copylistfiles.length;f++) {
                                                           copylistfolders  = copylistfiles[f].getName();
                                                              
                                                             String copyselectionss=request.getParameter("my_select1");
                                                 if(copyselectionss.equals(copylistfolders)){
                                             objWriterss.write("one"+"\n");
                                             objWriterss.write(copylistfiles[f].getName()+"\n");
                                            objWriterss.flush();
                                         objWriterss.close();
                                           
                                        }

                                      }
      //  <!--------------------------------Config path Run Trial Tracker-------------------------------------------------------------------->
                                  String pathcsv = "C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\MacroTrigger\\MacroTrigger.exe";
                                  File finishfiles = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\OneCondition\\comp.bin");
                                  File finishfile = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\");
                                  File[] checklistfiles = finishfile.listFiles();
                                  File filecsv = new File(pathcsv);
                                  filecsv.toURI();
                                  Process p = Runtime.getRuntime().exec("cmd /c start /wait "+filecsv);
                                  p.waitFor();

                    for(int c=0;c< checklistfiles.length;c++) {
                                            
                                          
                                              if (finishfiles.exists()) {
                                               out.println("<script type='text/javascript'>");
                                              out.println("show3s();");
                                              out.println("</script>");
                                           }else{
                                              out.println("<script type='text/javascript'>");
                                              out.println("checkederror();");
                                              out.println("</script>");
                                         }
                                         
             
                                  }
            
                                      }catch(IOException  e){  
                                          e.printStackTrace();  
                                       }    
                                 }

                               }

   if(request.getParameter("runscript1")==null&&request.getParameter("runscript2")==null&&request.getParameter("del1")==null&&request.getParameter("del3")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
                                subjectshow="";
                                ownershow=""; 
                                emailshow=""; 
                                productshow =""; 
                                showtrialid=""; 
                                showtestcode=""; 
                                showtestid=""; 
                                showpfcode=""; 
                                showhddnum=""; 
                                showprocess=""; 
                                showstdate=""; 
                                showendate=""; 
                                showinorex="";  
                                stdate="";
                                enddate="";
          }
         
           
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          </select>\r\n");
      out.write("    </div>\r\n");
      out.write("        </h4></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("        <td><h4>Status: </h4></td>\r\n");
      out.write("      <td width=\"252\"><p><font color=\"#999999\"><img border=\"0\" id=\"showinload\" src=\"DATA-INF/Image/a.gif\" class=\"hide\"/></font><img border=\"0\" \r\n");
      out.write("          id=\"showinok\" src=\"DATA-INF/Image/ok.png\" class=\"hide\" /></p></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("       <tr id=\"showoptionchoose\"> \r\n");
      out.write("    <td width=\"121\">&nbsp; </td>\r\n");
      out.write("        \r\n");
      out.write("    <td width=\"323\"><input type=\"submit\" id=\"save\" name=\"save\" value=\"ADD\" class=\"button\" ");
      out.print(add);
      out.write(" onclick=\"status1();\" />\r\n");
      out.write("        <input type=\"submit\" id=\"edittracker\" name=\"edittracker\" value=\"EDIT\" class=\"button\" disabled onclick=\"statusedit1();\" />\r\n");
      out.write("        <input type=\"submit\" id=\"del1\" name=\"del1\"  value=\"DELETE\" disabled class=\"button\" />\r\n");
      out.write("        <input type=\"submit\" id=\"runscript1\" name=\"runscript1\" value=\"ExcuteTracker\" disabled class=\"button\" onclick=\"wait();\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("        <td width=\"252\">&nbsp;</td>\r\n");
      out.write("         \r\n");
      out.write("      <td width=\"136\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("     </fieldset>\r\n");
      out.write("      <fieldset align=\"left\"  id=\"table2\" class=\"hide\">\r\n");
      out.write("\r\n");
      out.write("    <legend >\r\n");
      out.write("      <h1>Summary</h1>\r\n");
      out.write("        </legend>\r\n");
      out.write("    <table border=\"0\" bordercolor=\"#00000\"  >\r\n");
      out.write("      <tr>\r\n");
      out.write("    <td></td>\r\n");
      out.write("         <td width=\"324\" id=\"texture\" ><h4>Select Summary CSV File: \r\n");
      out.write("     <div class=\"styled-select\"> \r\n");
      out.write("         <select width=\"100%\"  name=\"my_selects\" id=\"select\" class=\"select\" onchange=\"change2();\">\r\n");
      out.write("            <option  value=\"No_Result.html\">Please Select Condition</option>\r\n");
      out.write("            <!--------------------------------Event show Condition File-------------------------------------------------------------------->\r\n");
      out.write("      ");

                            File appFolderz = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\");
                
                            File[] listz = appFolderz.listFiles();
                          
                          
                          
                             for(int i=0;i<listz.length;i++)
                        {
                              File filez = listz[i];   
           if (filez.isFile() && filez.getName().endsWith(".csv")) {
        
                              addlist = listz[i].getName();
            
                              out.print("<option id=\"\"value=\"" +addlist+ "\">"+addlist+"</option>");
                                          }   
                              
                               if(request.getParameter("del3")!=null&&request.getParameter("runscript1")==null&&request.getParameter("runscript2")==null&&request.getParameter("del1")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
                            
                                   String selection=request.getParameter("my_selects");
                                   
                              if(selection.equals(addlist )){
                        
                                list[i].delete();
                              
                                          subjectshow ="";
                                          ownershow ="";
                                          emailshow="";
                                          allshow="";
                                          yieldshow="";
                                          testtimeshows="";
                                          chisqaureshow="";
                                          productshow="";
                                          modeltypeshow="";
                                          showtrialid ="";
                                          showtestcode="";
                                          testcodeAshow="";
                                          testcodeBshow="";
                                          showtestid="";
                                          showpfcode="";
                                          showinorex="";
                                          showhddnum="";
                                          showprocess="";
                                          showstdate="";
                                          showendate="";
                                          samplingshow="";
                                          mfgidshows="";
                                          stdate="";
                                          enddate="";
                                }
                              }
                            }
                 if(request.getParameter("del3")!=null&&request.getParameter("runscript1")==null&&request.getParameter("runscript2")==null&&
                request.getParameter("del1")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
                                out.println("<script type='text/javascript'>");
                                out.println("show2s();");
                                out.println("</script>"); 
                              }

                             if(request.getParameter("runscript2")!=null&&request.getParameter("runscript1")==null&&request.getParameter("del1")==null&&request.getParameter("del3")==null&&request.getParameter("save")==null&&request.getParameter("save1")==null){
            
                                          subjectshow ="";
                                          ownershow ="";
                                          emailshow="";
                                          yieldshow="";
                                          testtimeshows="";
                                          chisqaureshow="";
                                          productshow="";
                                          modeltypeshow="";
                                          showtrialid ="";
                                          showtestcode="";
                                          testcodeAshow="";
                                          testcodeBshow="";
                                          showtestid="";
                                          showpfcode="";
                                          showinorex="";
                                          showhddnum="";
                                          showprocess="";
                                          showstdate="";
                                          showendate="";
                                          samplingshow="";
                                          mfgidshows="";
                                          stdate="";
                                          enddate="";

                                          String line;
                                          String pidInfo ="";
                                          Process j =Runtime.getRuntime().exec(System.getenv("windir") +"\\system32\\"+"tasklist.exe");
                                          BufferedReader input =  new BufferedReader(new InputStreamReader(j.getInputStream()));

                                          while ((line = input.readLine()) != null) {
                                           pidInfo+=line; 
                                          }

                                          input.close();
                //  <!--------------------------------Event Check run One File -------------------------------------------------------------------->
                                          if(pidInfo.contains("MacroTrigger.exe"))
                                          {
                                          
                                          out.println("<script>");
                                           out.println("checkederror1();");
                                          out.println("</script>");
                           
                                
                     }else{
                                      try{    
        
                                  File deleteFile = new File("C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\OneSummary\\ConditionFileList.csv");
                                      if(deleteFile.exists()){
                                    deleteFile.delete();
                                     }
                                         String pathoption = "C:\\Tomcat_9.0\\webapps\\te6\\TrialTrackerStatus\\Condition\\OneSummary\\ConditionFileList.csv";
                                        File optionfile = new File(pathoption);
                                    
                                        Writer objWriters = new BufferedWriter(new FileWriter(optionfile));
                                        
                                      File copyFile = new File("C:\\Tomcat_9.0\\webapps\\TrialTrackerStatus\\Condition\\");
                                      File[] copylistfile = copyFile.listFiles();
                                      for(int d=0;d<copylistfile.length;d++) {
                                                               copylistfolder  = copylistfile[d].getName();
                                                              
                                                             String copyselections=request.getParameter("my_selects");
                                                        
                                                        if(copyselections.equals(copylistfolder)){
                                         objWriters.write(copylistfile[d].getName()+","+"1"+"\n" );
                                         objWriters.flush();
                                        objWriters.close();
    //  <!--------------------------------Config path Run Trial Summary -------------------------------------------------------------------->
                                         String pathexcel = "C:\\Tomcat_9.0\\webapps\\te6\\TrialSummary\\MacroTrigger\\MacroTrigger.exe";
                                         File fileexcel = new File(pathexcel);
                                            fileexcel.toURI();
                                        Process runs = Runtime.getRuntime().exec("cmd /c start /wait " + fileexcel );
                                          runs.waitFor();
                                        }
                                        }
                                       out.println("<script type='text/javascript'>");
                                        out.println("show4s();");
                                        out.println("</script>");
                                       }catch(IOException e){  
                                          e.printStackTrace();  
           
                                       }         
                                          }
                                    }
                
      out.write("\r\n");
      out.write("          </select>\r\n");
      out.write("    </div>\r\n");
      out.write("        </h4></td>\r\n");
      out.write("         \r\n");
      out.write("       <td></td>\r\n");
      out.write("        <td><h4>Status: </h4></td>\r\n");
      out.write("      <td width=\"252\"><p><font color=\"#999999\"><img border=\"0\" id=\"showonload\" src=\"DATA-INF/Image/a.gif\" class=\"hide\"/></font><img border=\"0\" \r\n");
      out.write("          id=\"showonok\" src=\"DATA-INF/Image/ok1.png\" class=\"hide\" /></p></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("       <tr id=\"showoptionchoose\"> \r\n");
      out.write("    <td width=\"121\">&nbsp; </td>\r\n");
      out.write("        \r\n");
      out.write("      <td width=\"324\"><input type=\"submit\" id=\"save1\" name=\"save1\" value=\"ADD\" class=\"button\" onclick=\"status2();\" />\r\n");
      out.write("        <input type=\"submit\" id=\"editsummary\" name=\"editsummary\" value=\"EDIT\" class=\"button\" disabled onclick=\"statusedit2();\" />\r\n");
      out.write("    <input type=\"submit\" id=\"del3\" name=\"del3\"  value=\"DELETE\" disabled class=\"button\"/>\r\n");
      out.write("    <input type=\"submit\" id=\"runscript2\" name=\"runscript2\" value=\"GenerateReport\" disabled class=\"button\" onclick=\"wait1();\" />\r\n");
      out.write("      </td>\r\n");
      out.write("        \r\n");
      out.write("      <td width=\"263\">&nbsp;</td>\r\n");
      out.write("         \r\n");
      out.write("      <td width=\"124\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("  \r\n");
      out.write("        </table>\r\n");
      out.write("     </fieldset>\r\n");
      out.write("       <table width=\"997\" height=\"26\" border=\"0\" id=\"table3\" class=\"hide\">\r\n");
      out.write("      <tr> \r\n");
      out.write("        <td width=\"848\"></td>\r\n");
      out.write("        <td width=\"63\"><font id=\"download\"  color=\"#0F366A\">Download:</font></td>\r\n");
      out.write("    <td width=\"38\"  align=\"right\">  <a href='");
      out.print(powerpointlink2);
      out.write("' id=\"download2\" name=\"download2\" target=\"_blank\"  onclick=\"changeFunc1();\"> \r\n");
      out.write("          <font color=\"#0F366A\">[.ppt]</font></a> \r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"30\"><a href='");
      out.print(powerpointlink1);
      out.write("' id=\"download1\" name=\"download1\" target=\"_blank\"  onclick=\"changeFunc2();\"> \r\n");
      out.write("          <font color=\"#0F366A\">[.xls]</font></a></td></tr></table>\r\n");
      out.write("    \r\n");
      out.write("     <iframe id=\"powerpoint\" name=\"powerpoint\" height=\"590\" width=\"1020\" src=\"");
      out.print(powerpointfolder);
      out.write("\" class=\"hide\" ></iframe>\r\n");
      out.write("          <td width=\"53\"><select width=\"100%\"  name=\"my_selec\" class=\"hide\" id=\"my_selec\" >\r\n");
      out.write("       \r\n");
      out.write("           ");

                   
        File showpowerpoints = new File("C:\\Tomcat_9.0\\webapps\\te6\\DATA-INF\\Result_htm\\");
      File[] powerpointlistfiles = showpowerpoints.listFiles();
      String powerpointselects=request.getParameter("my_selects");
    String checkpower3 =""; 
    for(int j=0;j<powerpointlistfiles.length;j++) {
          File file1 = powerpointlistfiles[j];   
          if(file1.isFile() && file1.getName().endsWith(".htm")){
        checkpower3=powerpointlistfiles[j].getName().replaceFirst(".htm", ".csv").replaceAll(" ", "_");
           out.print("<option id=\"\"value=\"" +checkpower3+ "\">"+checkpower3+"</option>");
          }
        }
           
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    <b><marquee direction=\"left\"><h4>Support<font color=\"green\"> Google Chrome / Firefox web browser </font>but not support<font color=\"red\"> Internet Explorer web browser</font></h4></marquee></b>\r\n");
      out.write("\t<a href=\"TrialTrackerStatus/userGuide/Trial_tracker_user_guild.pptx\" title=\"How to use ?\"><b><H3>Read me please.</H3></b></a>\r\n");
      out.write("</form> \r\n");
      out.write("  \r\n");
      out.write("  </div>   \r\n");
      out.write("          ");
      out.write("<!-- ============================================Top Layout============================================================================== -->\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div align = \"right\" id=\"footer\">\r\n");
      out.write("\t\t<div id=\"footercontent\" align=\"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table align = \"center\">\t\r\n");
      out.write("\t\t&copy; HGST aWestern Digital company (Thailand) Limited. All rigths reserved\r\n");
      out.write("\t\t</table\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
