/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M1
 * Generated at: 2016-03-21 06:54:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hitachigst.prb.te.teweb.*;
import com.hitachigst.prb.itd.itdtools.util.*;

public final class testcode_005fenterpriserelatedwebsite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/PageLayout/footerlayout.jsp", Long.valueOf(1455876871114L));
    _jspx_dependants.put("/PageLayout/testcode_righttoplayout.jsp", Long.valueOf(1458092814077L));
    _jspx_dependants.put("/PageLayout/../testcode_topmenu.jsp", Long.valueOf(1457697117567L));
    _jspx_dependants.put("/PageLayout/testcode_lefttoplayout.jsp", Long.valueOf(1455876871152L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hitachigst.prb.te.teweb");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.hitachigst.prb.itd.itdtools.util");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");

	String apppath=application.getRealPath("");
	String webpath=request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"";
	new TeWebConfig(apppath,webpath);
	

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" />\r\n");
      out.write("<meta name=\"author\" content=\"Luka Cvrk (www.solucija.com)\" />\r\n");
      out.write("<meta name=\"description\" content=\"My Site\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"key, words\" />\r\n");
      out.write("\r\n");
	
		String version="";
		String webname="";
		webname=IniFilesReader.getReturnProperties("Local.Application","Application Name");	
		version=TeWebVersionControl.getVersion();
	
      out.write("\r\n");
      out.write("<title>\r\n");
 out.println(webname); 
      out.write("\r\n");
      out.write("</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"DATA-INF/CSS/style.css\" media=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("function MM_reloadPage(init) {  //reloads the window if Nav4 resized\r\n");
      out.write("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {\r\n");
      out.write("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}\r\n");
      out.write("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();\r\n");
      out.write("}\r\n");
      out.write("MM_reloadPage(true);\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
String menumode="testcode_enterpriserelatedwebsite.jsp";
      out.write(" \r\n");
      out.write("<!-- ----------------------Te Logo--------------------------- -->\r\n");
      out.write("<div id=\"Layer1\" style=\"position:absolute; left:3px; top:3px; width:84px; height:70px; z-index:1\"><img src=\"DATA-INF/Image/telogo.jpg\" width=\"275\" height=\"58\" /></div>\r\n");
      out.write("<!-- -------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------------------Left Layout -------------- -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <div id=\"left\"> \r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!-- ============================================Top Layout============================================================================== -->\t\r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write("      <table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"><!-- <img  src=\"DATA-INF/Image/telogo.jpg\" alt=\"Your Logo\" title=\"Your Logo\" /> --></td>\r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t  <td width=\"33%\"></td>\r\n");
      out.write("\t\t  <td width=\"34%\"></td>\r\n");
      out.write("\t\t</tr>   \t \r\n");
      out.write("     </table>  \r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"headerL\"> </div> \r\n");
      out.write("\t\r\n");
      out.write("\t   <!------------ Top left menu ------------------->\r\n");
      out.write("\t\t<!--****************************Closed Top left menu\r\n");
      out.write("\t\t<div class=\"boxright\" >  \r\n");
      out.write("\t\t   <div class=\"boxcenter\" > \r\n");
      out.write("\t\t       <div class=\"boxleft\" > </div>      \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> \t\t\t        \r\n");
      out.write("\t\tEnd of Closed code****************************-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- ---------------------------------------------- -->\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul id=\"side_menu\"><!--  %@ include file=\"testcode_leftmenu.jsp\" %  --></ul> \r\n");
      out.write("\t</div>\t \t \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("  <!-- ============================================Top Layout============================================================================== -->\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"right\">\r\n");
      out.write("\t\t   ");
      out.write("\r\n");
      out.write("<!-- ============================================Top Layout============================================================================== -->\t\r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write("      <table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"></td>\t\t  \r\n");
      out.write("\t\t  <td width=\"23%\"><img src=\"DATA-INF/Image/telogoempty.jpg\" alt=\"Your Logo\" title=\"Your Logo\" /></td>\r\n");
      out.write("\t\t  <td width=\"40%\"> <p>Version : ");
out.println(version); 
      out.write(" | <a href=\"#Top\">Logon: ");
out.println(session.getAttribute("s_username").toString().trim());
      out.write("</a><br /></p> </td>\t  \r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr> \r\n");
      out.write("\t\t  <td width=\"33%\"></td>\t\t  \r\n");
      out.write("\t\t  <td width=\"23%\"></td>\r\n");
      out.write("\t\t  <td width=\"40%\"></td>\r\n");
      out.write("\t\t</tr>   \t \r\n");
      out.write("     </table>  \r\n");
      out.write("     <div id=\"header-container\">\t\t  \t\r\n");
      out.write("\t\t  ");
      out.write("     <ul id=\"nav\"> \r\n");
      out.write("\t  ");

	    if (menumode.equals("testcode_home.jsp")){
	  
      out.write("\r\n");
      out.write("\t\t   <li><a href=\"home.jsp\">Home</a><li>      \r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a>\r\n");
      out.write("\t\t   <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>  \r\n");
      out.write("\t\t   \r\n");
      out.write("\t \r\n");
      out.write("\t   ");

	   } else if (menumode.equals("testcode_enterpriserelatedwebsite.jsp")) {
	   
      out.write("\r\n");
      out.write("\t   \t   <li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a>\r\n");
      out.write("\t\t   <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>    \r\n");
      out.write("\t   ");

	    }else if (menumode.equals("testcode_testtimemonitor.jsp")) {
	   
      out.write("\r\n");
      out.write("\t       <li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a> \r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\t\t   \r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>    \r\n");
      out.write("\t\t");

		}else if(menumode.equals("testcode_testtrialtracker.jsp")){
		
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a> \r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\t\t   \r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>\r\n");
      out.write("\t   ");

		}else if(menumode.equals("testcode_testtimeworkweek.jsp")){
		
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"home.jsp\">Home</a><li>\r\n");
      out.write("\t\t   <li><a href=\"testcode_home.jsp\">Test Code</a> \r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("                <li><a href=\"testcode_enterpriserelatedwebsite.jsp\">Enterprise Related Web site</a></li>\r\n");
      out.write("                <li><a href=\"testcode_testtimemonitor.jsp\">Test Time Monitor</a></li>\r\n");
      out.write("                 <li><a href=\"testcode_testtrialtracker.jsp\">Test Trial Tracker</a></li>\r\n");
      out.write("\t\t\t\t <li><a href=\"testcode_testtimeworkweek.jsp\">Test Time by WW</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t  </li>\t\t   \r\n");
      out.write("\t\t   <li><a href=\"Process Flow.html\">About us</a></li>      \r\n");
      out.write("\t\t   <li><a href=\"index.jsp\">Logout</a></li>\r\n");
      out.write("\t\t   ");

		}
	   
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br class=\"clear\" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t  </div>\t \r\n");
      out.write("\t</div>\r\n");
      out.write("\t \r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t   <div id=\"subheader\">\t\t\r\n");
      out.write("            </div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("  <table align=\"center\" width=\"69%\" height=\"69%\" border=\"0\" valign=\"top\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"65%\" height=\"211\" align=\"right\" valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td><div align=\"center\"></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td><div align=\"center\">\r\n");
      out.write("                <p align=\"left\"><font size=\"+1\"><strong><font color=\"#990000\">Related \r\n");
      out.write("                  Website for Enterprise product</font></strong></font> </p>\r\n");
      out.write("                <table border=\"1\" cellspacing=\"0\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("                  <tr bgcolor=\"#333333\"> \r\n");
      out.write("                    <td width=\"271\"><div align=\"left\"><font color=\"#FFFFFF\" size=\"3\"><strong>Link</strong></font></div></td>\r\n");
      out.write("                    <td width=\"802\"><font color=\"#FFFFFF\" size=\"3\"><strong>Description</strong></font></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><strong><font size=\"3\"><a href=\"http://tecode1.sanjose.hgst.com/\">TE \r\n");
      out.write("                        CODE1 </a></font></strong></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Test code release packge \r\n");
      out.write("                        for all enterprise product</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><strong><font size=\"3\"><a href=\"http://sidewinder.sanjose.hgst.com/twiki/bin/view/Srst/WebHome\">TWiki</a></font></strong></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Description of juggernaut \r\n");
      out.write("                        code specification (Application Factory,ErrorCode,PersistentDataObject,TestEvent,TraceEventDescription)</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td> <div align=\"left\"><strong><font size=\"3\"><a href=\"http://fiweb.sanjose.hgst.com/requests/\">Test \r\n");
      out.write("                        Code Change Request </a></font></strong></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Test code changes request \r\n");
      out.write("                        for enterprise SoC5 test code</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><strong><font size=\"3\"><a href=\"http://sjf41srv.sanjose.hgst.com/bugzilla/\">Bugzilla</a></font></strong></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Description of technical \r\n");
      out.write("                        information changes item for SoC5 test code</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><strong><font size=\"3\"><a href=\"http://fogbugz.rochester.hgst.com/\">FogBugz</a></font></strong></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Test code changes request \r\n");
      out.write("                        for enterprise SoC6 test code (Common code base)</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td> <div align=\"left\"><font size=\"3\"><strong><a href=\"http://persephone.snjmfg.mfg.hgst.com/\">WW \r\n");
      out.write("                        Servo</a></strong></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Sanjose Servo website \r\n");
      out.write("                        including HiLiter installation files , Servo Wiki and \r\n");
      out.write("                        etc</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\"><a href=\"http://tecodetracker.rochester.hgst.com/cdtracker\"><strong>Code \r\n");
      out.write("                        Tracker</strong></a></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Test code release tracker \r\n");
      out.write("                        for enterprise SoC6 test code</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\"><a href=\"http://fiweb.sanjose.hgst.com/training2013/\"><strong>CBF \r\n");
      out.write("                        Training Material</strong></a></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Training Material for \r\n");
      out.write("                        CBF Product</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><strong><font size=\"3\"><a href=\"http://fiweb.sanjose.hgst.com/training2012v3/\">MPS \r\n");
      out.write("                        Training Material</a></font></strong></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Training Material for \r\n");
      out.write("                        MPS Product</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\"><strong><a href=\"http://tecode1.sanjose.hgst.com/testtimes/\">Test \r\n");
      out.write("                        Time Road Map</a></strong></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Test time roadmaps for \r\n");
      out.write("                        enterprise product</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\"><strong><a href=\"http://fogbugz.rochester.hgst.com/default.asp?W1791\">HDD Vocabulary</a></strong></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">Related HDD Vocabulary</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                   <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\"><strong><a href=\"DocumentSharing\\HDD Terminology and Experiences.pdf\">HDD Terminology and Experiences</a></strong></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">HDD Terminology and Experiences</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\t\t\t\t  <tr bgcolor=\"#D5EAFF\"> \r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\"><strong><a href=\"DocumentSharing\\Fail F002 CEP product after resume R9.pptx\">HDD Terminology and Experiences</a></strong></font></div></td>\r\n");
      out.write("                    <td><div align=\"left\"><font size=\"3\">HDD Terminology and Experiences</font></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("                </table>\r\n");
      out.write("              </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr> \r\n");
      out.write("            <td><div align=\"center\"><font size=\"+1\"><strong></strong></font></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table> \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("<!-- ============================================Top Layout============================================================================== -->\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div align = \"right\" id=\"footer\">\r\n");
      out.write("\t\t<div id=\"footercontent\" align=\"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table align = \"center\">\t\r\n");
      out.write("\t\t&copy; HGST aWestern Digital company (Thailand) Limited. All rigths reserved\r\n");
      out.write("\t\t</table\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ================================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
